### ISSUE TITLE
SensioLab Insight configuration

### ISSUE THREAD

**Issue by jim-parry** [lonnieezell/CodeIgniter4#100]
Can we configure SL Insight to ignore the third party packages?
Kint, in particular, triggers a large number of deemed errors.
These should not be part of the framework analysis.

Would one answer be to keep third party stuff external to the system folder? eg in /vendor or in /thirdparty if we did not want to mess up conventional composer usage?

**Comment by lonnieezell** [comment]
Unfortunately - it doesn't have any settings for those types of things, just for which branch to use. 

I don't have a problem moving the third-party stuff to a different folder. (and you're right that vendor would probably cause conflicts).

From what I've seen in the past, once I ignore the error in their UI, it won't show again for that file until a change is submitted for it.

**Comment by jim-parry** [comment]
ok. we'll have to wait & see, re the config.

Would a different fodler for included stuff would be awkward outside system?
I think we would have to provide some aliasing for it, eg BORROWED_PATH (tongue in cheek), so that it could be moved outside an app as well as system, if we wanted a shared framework installation across apps.

Does SLInsight automatically follow all fodlers in a branch, or is configured to just look at "system"?

**Comment by lonnieezell** [comment]
Only config item is the branch, so it looks at everything in the branch.

**Comment by jim-parry** [comment]
Ok then. My comment about removing it as a badge is then even more valid, imho

**Comment by lonnieezell** [comment]
Agreed. Will do.
