### ISSUE TITLE
SL Insight - classes should be unique per PHP file?

### ISSUE THREAD

**Issue by jim-parry** [lonnieezell/CodeIgniter4#101]
SL Insight reports an "info" item: Keeping only one class per file is a standard in the PHP community, since it promotes interoperability and maintainability.

Excluding Kint, we have three violators: 
- system/Debug/CustomExceptions.php
- system/HTTP/Response.php
- system/Router/Router.php

Each of these defines one or more namespaced exceptions, for clarity.

It seems silly to have each of these in their own file, given that they basically extend a parent Exception class. I am not sure if having these in separate files would complicate things like the classmap or loading time.

Thoughts?

**Comment by lonnieezell** [comment]
As far as I'm concerned, there's nothing wrong with this. Some "purists" (like SLInsight, obviously) would disagree, but the only time those exceptions are used is if that class/file has already been loaded. If we stick with the purist route, then each of the 13+/- custom exceptions would require an additional file, which would have a performance impact at times. 

I understand why the rule is in there, and generally agree with it. It makes autoloading possible. It makes it easier for people to find things when working on new projects. Lots of good comes from that, I just happen to disagree that Exceptions should fall in that category. 

So - I vote to ignore SLInsights in this case.

**Comment by jim-parry** [comment]
Is there a way to configure SLInsight to suit our style?

**Comment by lonnieezell** [comment]
Nope. They provide pretty close to zero configuration. It's all or nothing. While they have quite a few really good checks in there, you have to really stay on top of it to make it worthwhile.

**Comment by jim-parry** [comment]
Agreed. 

It shouldn't be a badge on the repo then, but just something we run from time to time to see what they think of us "now".
