### ISSUE TITLE
Class 'Config\App' not found

### ISSUE THREAD

**Issue by exbit** [lonnieezell/CodeIgniter4#12]
Error

Class 'Config\App' not found

BASEPATH/CodeIgniter.php at line 163

155 
156 Hooks::trigger('pre_system');
157 
158 //--------------------------------------------------------------------
159 // Get our Request and Response objects
160 //--------------------------------------------------------------------
161 
162 $config = new \Config\App();
163 
164 $request  = is_cli()
165         ? Services::clirequest($config)
166         : Services::request($config);
167 $request->setProtocolVersion($_SERVER['SERVER_PROTOCOL']);
168 $response = Services::response();
169

**Comment by benedmunds** [comment]
v3 is not functional yet.  Please use v2.

**Comment by exbit** [comment]
Which version is it?

**Comment by benedmunds** [comment]
ha my bad, I replied to the wrong project

**Comment by lonnieezell** [comment]
First - you realize this hasn't been released, yet, right? Which means I can't support it a whole lot right now. :)

Additional details are always helpful, though: 

- how fresh is the code you're trying to install? 
- What OS are you running? 
- Have you tried debugging it at all yourself and, if so, what did you find?

**Comment by exbit** [comment]
latest revision - 852d49f
W10-x64+php-7.0.4RC1-Win32-VC14-x64+httpd-2.4.18-win64-VC14
if before
$config = new \Config\App();
add
require_once APPPATH.'Config/App.php';
is displayed
404 - File Not Found
Sorry! Cannot seem to find the page you were looking for.

**Comment by sv3tli0** [comment]
Interesting why there is a namespace "Config" and with that classes as Config/App ..
It should be Appnamespace/Config/App.

Those configurations are part of the application and I don't see what point may exist of having them under different namespace ?

One big minus will be if there exists and is used some namespace which is really common word as "Config" . I have met a few times problems related to same namespaces usage in a project and required  library loaded with Composer..

**Comment by lonnieezell** [comment]
@exbit - The autoloader should take care of finding that file for you. Strange that it's not, though I haven't run any tests on Windows yet, as I'm on a Mac. I guess it's finally time to upgrade Parallels so I can run some tests on Windows. :) Any chance you can step through the code with XDebug and see why it's not finding it in the autoloader until I have time to get a working Windows rig setup here again? 

@sv3tli0 There is the possibility of a namespace collision, using something simple like Config, true, although I don't know that I've ever seen that one show up. It was done to make it possible to change the App namespace and yet still allow system to know how to find the config files. Seems I tried using the constant and didn't have any luck in system files, but will have to investigate again.

**Comment by lonnieezell** [comment]
@exbit - did you find a solution for this other than simply requiring the file explicitly? I've finally got a setup up and running where I can start to explore it on Windows. Need to get xdebug installed and step through the code, but I'm out of time for today.

**Comment by exbit** [comment]
While no solution found, Timeline: Bootstrap
Routing Timer
Controller	Timer	
Controller Constructor
View: welcome_message.php - not to goes

index.php
require './vendor/autoload.php';

CodeIgniter.php
require APPPATH.'Config/App.php';
require APPPATH.'Config/Logger.php';

I think the problem is in the paths to the files

**Comment by lonnieezell** [comment]
I believe I found it. Filename sanitizer in Autoloader was doing too good of a job.
