### ISSUE TITLE
ci4 support websocket it?

### ISSUE THREAD

**Issue by phproot** [lonnieezell/CodeIgniter4#121]
ci4 support websocket it?
websocket should be a trend in the future.

**Comment by lonnieezell** [comment]
I would definitely like to, yes. But we're not that far along. :)

**Comment by jim-parry** [comment]
Questions like this should be raised on the forum ... http://forum.codeigniter.com/forum-29.html
We need to be careful & implement the balance of the core features in an orderly fashion.
