### ISSUE TITLE
Namespace for test case classes

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/CodeIgniter4#17]
The current test case classes has no namespace.
I think it is better they have also namespaces. It avoids class name collisions.

And in my opinion, it is the best that a test case class has the same namespace as the class under test.
In that case, we can write class names in test code with the same style as the class under test.

What do you think?

**Comment by lonnieezell** [comment]
I have no problem with those changes. Sounds like good organization. As long as it works without changing the autoloaders, I'm good. I look forward to the pull request.

**Comment by kenjis** [comment]
I sent PR: #19

**Comment by lonnieezell** [comment]
Merged. Thanks!
