### ISSUE TITLE
Test folder structure

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/CodeIgniter4#20]
Now we have only system test, and the `tests` folder is like this:

~~~
tests/
|--Autoloader/
|--CLI/
...
~~~

My question is where do we put application test files?

**Comment by lonnieezell** [comment]
My thought is that the system tests would be removed as part of a build script when getting a release ready. In most cases, users don't need those. 

I guess, though, that only applies to tagged release downloads. For those just cloning from git, they  would need a clean path for it, though that could be removed via a .gitattributes file. 

You are probably right, though, that we should put system tests into their own folder. 

tests/_system?

**Comment by kenjis** [comment]
I'm not yet sure where we put application test files.
how about when we use modules?

~~~
application/
blog_module/
~~~

1)

~~~
application/
blog_module/
tests/application/
tests/blog_module/
~~~

2)

~~~
application/
application/tests/
blog_module/
blog_module/tests/
~~~

Is 2) better?

**Comment by narfbg** [comment]
1 is always better, because autoloaders.

**Comment by kenjis** [comment]
@narfbg What do you mean by *because autoloaders*?

**Comment by narfbg** [comment]
Assuming PSR-4, which is something we have here:

    new App\tests\Foo(); // will do an include(APPPATH.'tests/Foo.php')

If the file exists, of course.

**Comment by kenjis** [comment]
Why 1) is always better? Sorry, I can't get your point.

**Comment by narfbg** [comment]
Take my previous comment, and note that the 'App' namespace is coupled with `APPPATH` path, which is both different from and not a parent of tests/.

**Comment by narfbg** [comment]
In other words, structure 1 is used, the autoloader won't (mistakenly) try to load your tests as legitimate application code, while that happens if you use the 2nd structure.

**Comment by kenjis** [comment]
I got your point.

3)
~~~
application/
tests/
blog_module/src/
blog_module/tests/
~~~

**Comment by lonnieezell** [comment]
I agree with @narfbg  on this one, though, past a certain point, it's not up to us a framework developers since we're not developing the app. Either 1 or 3 works just fine. I would we build with the assumption people are going to put their app tests in `tests/application`. We can even provide a blank directory for that. After that point, they can do whatever they desire.

**Comment by kenjis** [comment]
The following is the best for us?

~~~
application/
tests/application/
tests/system/
~~~

We can write `phpunit.xml` like below:

~~~
	<testsuites>
		<testsuite name="system">
			<directory suffix=".php">./tests/system</directory>
		</testsuite>
		<testsuite name="application">
			<directory suffix=".php">./tests/application</directory>
		</testsuite>
	</testsuites>
~~~

**Comment by lonnieezell** [comment]
Yes, I believe so.

**Comment by kenjis** [comment]
Thanks guys.
I sent PR to move test case files to `tests/system` folder. #28
