### ISSUE TITLE
exit() prevents from testing

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/CodeIgniter4#31]
There are still some `exit()`s. It stops phpunit. We can't test.

See <https://github.com/kenjis/ci-phpunit-test/blob/master/docs/RequestsToCodeIgniter.md#functions-which-dont-call-exit>.

I hope at least to remove `exit()` in helper functions.

**Comment by kenjis** [comment]
In the case of `redirect()`, if we want to keep the function same as before (it seems the current implementation is it), I think we have to throw an exception, instead of calling `exit()`.

Catching the exception in `CodeIgniter.php` and go to the end of the file. So we don't have to call `exit()` and we can exit CodeIgniter safely.

I don't know another way to remove `exit()` in the code now.

**Comment by lonnieezell** [comment]
I think you're right about how to handle the `redirect()` method. And that provides the best reasoning to encapsulate CodeIgniter as a class, honestly. 

We want to be able to provide the exit codes so we can continue to provide the responses during exits for other scripts to monitor. We can pass those exit codes in the exceptions. Additionally, different types of exceptions can be provided for the more severe log levels, allowing the system to take some automatic action when those types of errors happen. 

All of that works cleanest with CI as an object. I still have other objections/concerns about some of the details in your class, though. :)

**Comment by kenjis** [comment]
Removed `exit()` in `redirect()`: #49

**Comment by lonnieezell** [comment]
So are we good close this, then? That was the main blocker, right?
