### ISSUE TITLE
Rename the loader class

### ISSUE THREAD

**Issue by vonalbert** [lonnieezell/CodeIgniter4#39]
I see the Loader Class does not actually load a file, but it just locates non-class files. Hence I propose rename it to FileLocator and move it under the CodeIgniter\Autoloader namespace.

If you're ok with it I can take the burden :)

**Comment by lonnieezell** [comment]
That sounds good. Originally, I thought there was going to end up being more in there, but it looks like we might not need more than that, so this rename makes sense.

**Comment by vonalbert** [comment]
Ok, I'll make a PR as soon I can. Want me to move it also under the Autoloader namespace or it can stay where it is?

**Comment by lonnieezell** [comment]
Moving to autoloader namespace sounds good.

**Comment by vonalbert** [comment]
:+1:
