### ISSUE TITLE
Why IncomingRequest has setCookie()?

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/CodeIgniter4#52]
https://github.com/lonnieezell/CodeIgniter4/blob/develop/system/HTTP/IncomingRequest.php#L307
It sets a cookie to a response, doesn't it?

**Comment by lonnieezell** [comment]
You're right. It does belong in the response. I'm sure it got left there simply because it was in the Input class in CI3.

**Comment by kenjis** [comment]
Okay, I hope the Response class has cookie data.
So that we can test cookie data like: https://github.com/kenjis/ci-phpunit-test/blob/master/docs/FunctionAndClassReference.md#testcaseassertresponsecookiename-value-allow_duplicate--false
