### ISSUE TITLE
BaseConfig getEnvValue type juggling

### ISSUE THREAD

**Issue by mwhitneysdsu** [lonnieezell/CodeIgniter4#67]
For reference, the content of `getEnvValue()` currently looks like this:

```php
if ($value = getenv("{$shortPrefix}.{$property}"))
		{
			return $value;
		}
		else if ($value = getenv("{$prefix}.{$property}"))
		{
			return $value;
		}
		else if ($value = getenv($property))
		{
			return $value;
		}
```

This would appear to prevent setting values such as 0, "0", an empty string, empty array, etc. You've worked around the boolean false by allowing conversion of the string 'false' in the constructor, but most of the other loose comparisons still apply within the `getEnvValue()` method itself. Fixing this would likely require three separate if comparisons using `$value === false`.

**Comment by lonnieezell** [comment]
Hey, Mat, good to hear from you!

But, dang, you're right. Good catch!

**Comment by mwhitneysdsu** [comment]
I probably wouldn't have noticed it if it weren't for the update you made to convert `'false'` to `false`, because that just sets off alarms in my head. Unfortunately, since `getenv()` returns `false` when it can't find the value, it leads us to the land of choosing between a series of bad options.
