### ISSUE TITLE
Database Connection setDatabase() and getVersion() methods

### ISSUE THREAD

**Issue by mwhitneysdsu** [lonnieezell/CodeIgniter4#68]
In the BaseConnection and MySQLi\Connection, `setDatabase()` and `getVersion()` are missing their access/visibility keywords:

```php
abstract function setDatabase(string $databaseName);
abstract function getVersion();

function setDatabase(string $databaseName)
{
}

function getVersion()
{
}
```

I would assume they should be public, but I figured I'd call it out just in case.

**Comment by lonnieezell** [comment]
Correct. Those were the results of simply porting the functions over.
